---
title: "p8105_hw5_zf2211"
author: "Francis"
date: "11/6/2018"
output: github_document
---
### Problem 1
```{r}
#load packages
library(tidyverse)
```

```{r}
# conbine all file names into one dataframe
file = as.data.frame(list.files(path = "./data")[1:20]) 
# rename column
colnames(file)[1] = 'path'
```

```{r}
# create a function to read data one by one 
read_files = function (path) {
  df = 
    read.csv(str_c("./data/", path)) %>% 
    janitor::clean_names() %>% 
    as.data.frame()
  df
}
```

```{r}
# save the results as new variables in the dataframe
data <- 
  map(file$path, read_files) %>% 
  bind_rows()
data <- 
bind_cols(file, data)
```

```{r}
## tidy dataset
# transform the dataframe in one colume
# clean variable names
data <-  
  data %>% 
  gather(key = week, value = value, week_1:week_8) %>% 
  separate(path, into = c("group", "appendix"), sep = "_") %>% 
  separate(appendix, into = c("ID", "remove_1"), sep = 2 ) %>% 
  separate(week, into = c("remove_2", "week"), sep = "_") %>% 
  select(-remove_1, -remove_2) %>% 
  mutate(group = as.factor(group)) %>% 
  arrange(group, ID, week)
```


